name: 02 - Workflow Events

on: workflow_dispatch

jobs:
  echo-show-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I was triggered by ${{ github.event_name }} event."
