name: 04 - Using Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Step
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        working-directory: 04-using-actions/gh-actions-app
        run: npm ci
    #   - name: Setup node Step
    #     working-directory: 04-using-actions/gh-actions-app
    #     run: npm ci

    #   - name: Install Dependencies
    #     run: echo "Setup node"  