name: 06-Contexts

on:
    - push
    - workflow_dispatch

jobs :
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Even Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "Ref: ${{ github.sha }}"
                echo "Ref: ${{ github.actor }}"
            - name: Retrieve Variable
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"
