name: 07 - Using Expressions

run-name: 07 - Using Expressions | DEBUG ${{ inputs.debug && 'ON' || 'OFF' }}


env:
    # MY_WORKFLOW_WITH_DEFAULT: ${{ vars.MY_VAR || 'default value' }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        if: github.event_name == 'push'
        run: echo "I was triggered by a push event"
